USE master
GO

CREATE DATABASE CLINICA_DB
GO

USE CLINICA_DB
GO

CREATE TABLE Permisos(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Puestos(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Areas(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Especialidades(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Estados(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Dias(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Usuario VARCHAR(20) NOT NULL,
	Clave VARCHAR(20) NOT NULL,
	IdPermiso INT NULL FOREIGN KEY REFERENCES Permisos(Id),
	Activo BIT NOT NULL DEFAULT 1
)
GO

CREATE TABLE Personas(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Dni VARCHAR(8) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Telefono VARCHAR(20) NULL,
	UrlImagen VARCHAR(200) NULL,
	IdUsuario INT NULL FOREIGN KEY REFERENCES Usuarios(Id),
	Activo BIT NOT NULL DEFAULT 1
)
GO

CREATE TABLE Personal(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	IdArea INT NULL FOREIGN KEY REFERENCES Areas(Id),
	IdPuesto INT NULL FOREIGN KEY REFERENCES Puestos(Id),
	IdPersona INT NOT NULL FOREIGN KEY REFERENCES Personas(Id)
)
GO

CREATE TABLE Pacientes(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	IdPersona INT NOT NULL FOREIGN KEY REFERENCES Personas(Id),
)
GO

CREATE TABLE Medicos(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Matricula VARCHAR(20) NOT NULL,
	IdPersona INT NOT NULL FOREIGN KEY REFERENCES Personas(Id),
)
GO

CREATE TABLE HorariosPorMedicos(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	IdDia INT NOT NULL FOREIGN KEY REFERENCES Dias(Id),
	HoraEntrada TIME NOT NULL,
	HoraSalida TIME NOT NULL,
	IdMedico INT NOT NULL FOREIGN KEY REFERENCES Medicos(Id)
)
GO

CREATE TABLE EspecialidadPorMedico(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	IdMedico INT NOT NULL FOREIGN KEY REFERENCES Medicos(Id),
	IdEspecialidad INT NOT NULL FOREIGN KEY REFERENCES Especialidades(Id)
)
GO

CREATE TABLE Turnos(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Fecha DATETIME NOT NULL,
	Observaciones VARCHAR(250) NULL,
	IdMedico INT NOT NULL FOREIGN KEY REFERENCES Medicos(Id),
	IdPaciente INT NOT NULL FOREIGN KEY REFERENCES Pacientes(Id),
	IdEspecialidad INT NOT NULL FOREIGN KEY REFERENCES Especialidades(Id),
	IdEstado INT NOT NULL FOREIGN KEY REFERENCES Estados(Id)
)
GO

CREATE TABLE HistoriaClinica(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	Descripcion VARCHAR(250) NOT NULL,
	Fecha DATETIME NOT NULL,
	IdMedico INT NOT NULL FOREIGN KEY REFERENCES Medicos(Id),
	IdPaciente INT NOT NULL FOREIGN KEY REFERENCES Pacientes(Id)
)
GO